services:
  spring-boot-webflux-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
