apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonfly-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dragonfly
  template:
    metadata:
      labels:
        app: dragonfly
    spec:
      nodeSelector:
        role: processor
      containers:
        - name: dragonfly
          image: dragonfly/dragonfly:latest
          ports:
            - containerPort: 6380
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-service
spec:
  selector:
    app: dragonfly
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6380
  clusterIP: None