apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dragonfly
  template:
    metadata:
      labels:
        app: dragonfly
    spec:
      nodeSelector:
        role: processor
      containers:
        - name: dragonfly
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-service
spec:
  selector:
    app: dragonfly
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer