apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32248
      protocol: TCP
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana

