apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      nodeSelector:
        role: processor  # Ensures this pod runs only on the node labeled 'role=processor'
      containers:
        - name: processor
          image: ghcr.io/levi-darasa/betting/processor:latest
          ports:
            - containerPort: 8081
            - containerPort: 19090
          resources:
            requests:
              cpu: "16"
              memory: "32Gi"
            limits:
              cpu: "32"
              memory: "64Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: processor-grpc-service
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 19090
      targetPort: 19090
  type: LoadBalancer
