apiVersion: v1
kind: Service
metadata:
  name: sender-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: LoadBalancer
  selector:
    app: sender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

