apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ip-10-89-15-94.ap-east-1.compute.internal  # Specify that sender runs on this node
      containers:
        - name: sender
          image: ghcr.io/levi-darasa/betting/sender:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "13"
              memory: "18Gi"
            limits:
              cpu: "20"
              memory: "26Gi"

