apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      nodeSelector:
        role: sender
      containers:
        - name: sender
          image: ghcr.io/levi-darasa/betting/sender:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "13"
              memory: "18Gi"
            limits:
              cpu: "20"
              memory: "26Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: sender-service
spec:
  type: LoadBalancer
  selector:
    app: sender
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080