apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      nodeSelector:
        role: sender  # Ensures this pod runs only on the node labeled 'role=sender'
      containers:
        - name: sender
          image: ghcr.io/levi-darasa/betting/sender:latest
          ports:
            - containerPort: 8080
          env:
            - name: GRPC_HOST
              value: "10.89.15.92:19090"