apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      nodeSelector:
        role: sender
      containers:
        - name: sender
          image: ghcr.io/levi-darasa/betting/sender:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "16"
              memory: "32Gi"
            limits:
              cpu: "32"
              memory: "64Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: sender-service
spec:
  type: LoadBalancer
  selector:
    app: sender
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080