server:
  port: 8080
  error:
    include-stacktrace: always
spring:
  profiles:
    active: prod
  application:
    name: sender
  jmx:
    enabled: false
  main:
    web-application-type: reactive

logging:
  level:
    reactor:
      core:
        publisher:
          Hooks: info
grpc:
  client:
    bet-service:
      address: dns:///10.89.15.92:19090
      negotiation-type: plaintext
      max-inbound-message-size: 10485760  # 10MB
      keep-alive-time: 30s
      keep-alive-timeout: 10s
      keep-alive-without-calls: true
      enable-keep-alive: true