apiVersion: v1
kind: Service
metadata:
  name: dragonfly
spec:
  selector:
    app: dragonfly
  ports:
    - protocol: TCP
      port: 6380  # Expose to this port
      targetPort: 6379  # Internal container port
  type: LoadBalancer
