apiVersion: apps/v1
kind: Deployment
metadata:
  name: dragonfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dragonfly
  template:
    metadata:
      labels:
        app: dragonfly
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname  # Key to match the node name
                    operator: In
                    values:
                      - ip-10-89-15-92.ap-east-1.compute.internal  # Target node
      containers:
        - name: dragonfly
          image: docker.dragonflydb.io/dragonflydb/dragonfly
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: dragonfly-data
              mountPath: /data
          resources:
            requests:
              cpu: "4"
              memory: "6Gi"
            limits:
              cpu: "6"
              memory: "12Gi"
      volumes:
        - name: dragonfly-data
          persistentVolumeClaim:
            claimName: dragonfly-pvc

