name: Build & Push Sender & Processor Images to GHCR

on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Common, Sender & Processor JARs
        run: mvn clean package -DskipTests

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Sender Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/sender:latest -f sender/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/sender:latest

      - name: Build & Push Processor Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/processor:latest -f processor/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/processor:latest
