name: Build and Deploy Spring Boot Services

on:
  push:
    branches:
      - main  # Trigger this action on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner for building
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Archive JAR files
        run: |
          mkdir -p build-artifacts
          cp sender/target/sender-*.jar build-artifacts/
          cp processor/target/processor-*.jar build-artifacts/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jars
          path: build-artifacts/

  #  deploy_sender:
  #    runs-on: sender-runner  # Run this on Server 1
  #    needs: build
  #    steps:
  #      - name: Download sender JAR
  #        uses: actions/download-artifact@v4
  #        with:
  #          name: spring-boot-jars
  #          path: build-artifacts/
  #
  #      - name: Deploy Sender Service
  #        run: |
  #          mv build-artifacts/sender-*.jar /home/gaconlonton/jars/
  #          sudo systemctl restart sender  # Restart the sender service

  deploy_processor:
    runs-on: processor-runner  # Run this on Server 2
    needs: build
    steps:
      - name: Download processor JAR
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-jars
          path: build-artifacts/

      - name: Deploy Processor Service
        run: |
          mv build-artifacts/processor-*.jar /home/gaconlonton/jars/
          sudo systemctl restart processor  # Restart the processor service
